/**
 * This file was automatically generated by templates/migrators_mod.hbs.
 * DO NOT MODIFY IT BY HAND. Instead, modify templates/migrators_mod.hbs,
 * and run build script to regenerate this file.
 */

pub mod from_0_1_0_to_0_2_0;
