var sourcesIndex = JSON.parse('{\
"polywrap":["",[],["lib.rs"]],\
"polywrap_client":["",[],["client.rs","lib.rs","subinvoker.rs"]],\
"polywrap_client_builder":["",[],["lib.rs","polywrap_base_resolver.rs","polywrap_client_config.rs","polywrap_client_config_builder.rs"]],\
"polywrap_client_default_config":["",[["embeds",[["fs_resolver",[],["mod.rs"]],["http_resolver",[],["mod.rs"]],["ipfs_http_client",[],["mod.rs"]],["ipfs_resolver",[],["mod.rs"]]],["mod.rs"]]],["lib.rs","system_config.rs","web3_config.rs"]],\
"polywrap_core":["",[["resolution",[],["get_uri_resolution_path.rs","helpers.rs","mod.rs","uri_resolution_context.rs","uri_resolver.rs"]]],["client.rs","error.rs","file_reader.rs","interface_implementation.rs","invoker.rs","lib.rs","package.rs","redirects.rs","uri_resolver_handler.rs","wrap_invoker.rs","wrap_loader.rs","wrapper.rs"]],\
"polywrap_core_macros":["",[],["lib.rs"]],\
"polywrap_ethereum_wallet_plugin":["",[["wrap",[],["mod.rs","module.rs","types.rs","wrap.info.rs"]]],["connection.rs","connections.rs","lib.rs","networks.rs","types.rs"]],\
"polywrap_fs_plugin":["",[["wrap",[],["mod.rs","module.rs","types.rs","wrap.info.rs"]]],["lib.rs"]],\
"polywrap_http_plugin":["",[["wrap",[],["mod.rs","module.rs","types.rs","wrap.info.rs"]]],["lib.rs","parse_request.rs","parse_response.rs"]],\
"polywrap_logger_plugin":["",[["wrap",[],["mod.rs","module.rs","types.rs","wrap.info.rs"]]],["lib.rs"]],\
"polywrap_native":["",[["mocks",[],["mod.rs","wrapper.rs"]],["resolvers",[],["_static.rs","ffi_resolver.rs","mod.rs","recursive.rs","resolution_context.rs","uri_package_or_wrapper.rs"]]],["builder.rs","client.rs","error.rs","invoker.rs","lib.rs","package.rs","polywrap_native.rs","uri.rs","wrapper.rs"]],\
"polywrap_plugin":["",[],["error.rs","lib.rs","method.rs","module.rs","package.rs","with_methods.rs","wrapper.rs"]],\
"polywrap_plugin_implementor":["",[],["lib.rs"]],\
"polywrap_resolver_extensions":["",[],["extendable_uri_resolver.rs","lib.rs","uri_resolver_wrapper.rs"]],\
"polywrap_resolvers":["",[["cache",[],["basic_resolution_result_cache.rs","basic_wrapper_cache.rs","mod.rs","resolution_result_cache.rs","wrapper_cache.rs"]]],["base_resolver.rs","lib.rs","package_resolver.rs","package_to_wrapper_resolver.rs","recursive_resolver.rs","redirect_resolver.rs","resolution_result_cache_resolver.rs","resolver_vec.rs","resolver_with_loop_guard.rs","simple_file_resolver.rs","static_resolver.rs","uri_resolver_aggregator.rs","uri_resolver_aggregator_base.rs","wrapper_cache_resolver.rs","wrapper_resolver.rs"]],\
"polywrap_uri":["",[],["lib.rs"]],\
"polywrap_wasm":["",[["runtime",[],["imports.rs","instance.rs","mod.rs"]]],["error.rs","file_reader.rs","lib.rs","wasm_module.rs","wasm_package.rs","wasm_wrapper.rs"]],\
"uniffi_bindgen":["",[],["uniffi-bindgen.rs"]]\
}');
createSourceSidebar();
