/**
 * This file was automatically generated by templates/formats.hbs.
 * DO NOT MODIFY IT BY HAND. Instead, modify templates/formats.hbs,
 * and run build script to regenerate this file.
 */

use serde_json::Value;
use serde::{Serialize, Deserialize};
use polywrap_schemafy::schemafy;

schemafy!(
  root: WrapManifest01
  "schemas/0.1.json"
);


#[derive(Clone)]
pub enum AnyManifest {
  WrapManifest01(WrapManifest01),
}

impl AnyManifest {
  pub fn format(&self) -> String {
    match self {
      AnyManifest::WrapManifest01(_) => "0.1".to_string(),
    }
  }

    pub fn from_json_value(value: Value) -> Self {
        match value["format"].as_str().unwrap() {
            "0.1" => AnyManifest::WrapManifest01(serde_json::from_value(value).unwrap()),
            _ => panic!("Invalid manifest format"),
        }
    }

    pub fn to_json_value(&self) -> Value {
        match self {
            AnyManifest::WrapManifest01(manifest) => serde_json::to_value(manifest).unwrap(),
        }
    }
}

pub const LATEST_MANIFEST_FORMAT: &str = "0.1";
pub type WrapManifest = WrapManifest01;