/**
 * This file was automatically generated by templates/versions.hbs.
 * DO NOT MODIFY IT BY HAND. Instead, modify templates/versions.hbs,
 * and run build script to regenerate this file.
 */

use serde_json::Value;
use serde::{Serialize, Deserialize};
use polywrap_schemafy::schemafy;
use crate::utils::sanitize_semver_version;

schemafy!(
  root: WrapManifest01
  "schemas/0.1.json"
);


#[derive(Clone)]
pub enum AnyManifest {
  WrapManifest01(WrapManifest01),
}

impl AnyManifest {
  pub fn version(&self) -> String {
    match self {
      AnyManifest::WrapManifest01(_) => sanitize_semver_version("0.1"),
    }
  }

    pub fn from_json_value(value: Value) -> Self {
        match value["version"].as_str().unwrap() {
            "0.1" => AnyManifest::WrapManifest01(serde_json::from_value(value).unwrap()),
            _ => panic!("Invalid manifest version"),
        }
    }

    pub fn to_json_value(&self) -> Value {
        match self {
            AnyManifest::WrapManifest01(manifest) => serde_json::to_value(manifest).unwrap(),
        }
    }

    pub fn get_latest_version() -> String {
        sanitize_semver_version("0.1")
    }
}

pub type WrapManifest = WrapManifest01;