(function() {var implementors = {
"polywrap_core":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"polywrap_core/error/enum.Error.html\" title=\"enum polywrap_core::error::Error\">Error</a>"]],
"polywrap_ethereum_wallet_plugin":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"polywrap_ethereum_wallet_plugin/connection/enum.WalletError.html\" title=\"enum polywrap_ethereum_wallet_plugin::connection::WalletError\">WalletError</a>"]],
"polywrap_fs_plugin":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"polywrap_fs_plugin/enum.FileSystemPluginError.html\" title=\"enum polywrap_fs_plugin::FileSystemPluginError\">FileSystemPluginError</a>"]],
"polywrap_http_plugin":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"polywrap_http_plugin/enum.HttpPluginError.html\" title=\"enum polywrap_http_plugin::HttpPluginError\">HttpPluginError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"polywrap_http_plugin/parse_response/enum.ParseResponseError.html\" title=\"enum polywrap_http_plugin::parse_response::ParseResponseError\">ParseResponseError</a>"]],
"polywrap_native":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"polywrap_native/resolvers/uri_package_or_wrapper/enum.FFIUriPackageOrWrapperKind.html\" title=\"enum polywrap_native::resolvers::uri_package_or_wrapper::FFIUriPackageOrWrapperKind\">FFIUriPackageOrWrapperKind</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"polywrap_native/uri/struct.FFIUri.html\" title=\"struct polywrap_native::uri::FFIUri\">FFIUri</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"polywrap_native/error/enum.FFIError.html\" title=\"enum polywrap_native::error::FFIError\">FFIError</a>"]],
"polywrap_plugin":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"polywrap_plugin/error/enum.PluginError.html\" title=\"enum polywrap_plugin::error::PluginError\">PluginError</a>"]],
"polywrap_uri":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"polywrap_uri/struct.ParseError.html\" title=\"struct polywrap_uri::ParseError\">ParseError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"polywrap_uri/struct.Uri.html\" title=\"struct polywrap_uri::Uri\">Uri</a>"]],
"polywrap_wasm":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.72.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"polywrap_wasm/error/enum.WrapperError.html\" title=\"enum polywrap_wasm::error::WrapperError\">WrapperError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()